// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlttchszkjgpqognmtye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdHRjaHN6a2pncHFvZ25tdHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTI0MzUsImV4cCI6MjA3Mjk4ODQzNX0._nLXMu5EImKGfSwwhLEBCAKPjxMRCG5dhEvmF_c9lts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});